// src/routes/about/SkillCard.svelte
<script lang="ts">
	import { StarRegular, StarSolid } from 'svelte-awesome-icons';

	export let name: string;
	export let icon: string;
	export let stars: number | undefined = undefined;
</script>

<div class="p-2 flex flex-col items-center border-2 rounded gap-1">
	<img src={icon} alt={name} class="w-10" />
	<span>{name}</span>
	{#if stars}
		<div class="flex justify-center">
			{#each [1, 2, 3, 4, 5] as star}
				{#if star <= stars}
					<StarSolid size="1rem" color="#FACC15" />
				{:else}
					<StarRegular size="1rem" color="#FACC15" />
				{/if}
			{/each}
		</div>
	{/if}
	<slot />
</div>

// src/components/skillCard/components/SkillCard.tsx
import { ReactNode } from 'react';
import Image from 'next/image';
import { type IconType } from 'react-icons';
import { MdStar, MdStarBorder } from 'react-icons/md';

export const SkillCard = ({
  name,
  icon: Icon,
  iconColor,
  iconSrc,
  stars,
  children,
}: {
  name: string;
  icon?: IconType;
  iconColor?: string;
  iconSrc?: string;
  stars?: number;
  children?: ReactNode;
}) => {
  return (
    <div className='flex flex-col items-center justify-evenly gap-1 rounded border-2 p-2'>
      {Icon && <Icon size='2.5rem' color={iconColor} />}
      {iconSrc && (
        <div className='relative aspect-square h-10'>
          <Image fill src={iconSrc} alt={name} className='object-contain' />
        </div>
      )}

      <p>{name}</p>

      {stars && (
        <div className='flex justify-center'>
          {[1, 2, 3, 4, 5].map((star) =>
            star <= stars! ? (
              <MdStar key={star} size='1rem' className='text-yellow-500' />
            ) : (
              <MdStarBorder key={star} size='1rem' className='text-yellow-400' />
            ),
          )}
        </div>
      )}

      {children}
    </div>
  );
};
