// src/components/pages/About.tsx
import classNames from 'classnames';
import { useState } from 'react';
import { IconContext } from 'react-icons';
import { RiArrowDownSLine, RiArrowUpSLine } from 'react-icons/ri';
import { H2 } from '@/components/atoms/H2';
import { H3 } from '@/components/atoms/H3';
import { IconLink } from '@/components/atoms/IconLink';

export const About = () => {
  const [isDetailsOpened, setDetailsOpened] = useState(false);

  return (
    <section id='about' className='mx-4 sm:mx-[10vw]'>
      <H2 title='ABOUT' />
      <div className='my-4'>
        <p className='my-4 text-5xl font-bold tracking-tight'>Hitsuji Rere</p>
        <p className='text-gray-600'>情報系工業高等専門学校 5年</p>
      </div>
      <div className='my-4 space-y-1'>
        <p>私は「好奇心」がとても強く、何にでも興味があります。</p>
        <p>
          ProcessingやSiv3D、Unityでゲームを作ったり、Node.jsでバックエンドを、Next.jsでフロントエンドをしています。
        </p>
        <p>またオリジナルのプログラミング言語を作ったり、競技プログラミングを楽しんでいます。</p>
      </div>
      <div className='my-4 flex flex-col gap-2 sm:flex-row sm:gap-4'>
        <IconLink text='@HitsujiRere' to='https://twitter.com/HitsujiRere' icon='twitter' />
        <IconLink text='HitsujiRere' to='https://github.com/HitsujiRere' icon='github' />
      </div>

      <div
        className={classNames('space-y-8 overflow-hidden transition-all duration-1000', {
          'max-h-screen opacity-100': isDetailsOpened,
          'max-h-0 opacity-0': !isDetailsOpened,
        })}
      >
        <section>
          <H3 title='AWARDS' />
          <ul className='space-y-2'>
            <li>第2回全国高等専門学校 ディープラーニングコンテスト2021 : 7位</li>
            <li>Hokuriku Innovation Trial-2020 : ICTまちづくり賞 </li>
            <li>パソコン甲子園2020 プログラミング部門 : 本選出場</li>
            <li>
              全国高専プログラミングコンテスト 第31回苫小牧大会(2020)
              <ul className='ml-8'>
                <li>自由部門 : 特別賞</li>
                <li>パテント審査部門 : 奨励賞</li>
              </ul>
            </li>
          </ul>
        </section>
        <section>
          <H3 title='CERTIFICATION' />
          <ul className='space-y-2'>
            <li>ITパスポート</li>
          </ul>
        </section>
        <section>
          <H3 title='PARTTIME-JOB' />
          <ul className='space-y-2'>
            <li>株式会社エニーアップ：2022年6月~</li>
          </ul>
        </section>
      </div>

      <div className='flex justify-center'>
        <button
          className='px-4 py-2 duration-500 hover:scale-110'
          onClick={() => setDetailsOpened(!isDetailsOpened)}
        >
          <div className='select-none text-2xl'>
            <IconContext.Provider value={{ size: '2rem' }}>
              {isDetailsOpened ? <RiArrowUpSLine /> : <RiArrowDownSLine />}
            </IconContext.Provider>
          </div>
        </button>
      </div>
    </section>
  );
};

// src/routes/about/+page.svelte
<script lang="ts">
	import { skillicons } from '$lib/funcs/skillicons';
	import { TwitterBrand, GithubBrand, PersonDiggingSolid } from 'svelte-awesome-icons';
	import SkillCard from './SkillCard.svelte';
	import { Timeline, TimelineItem } from '$lib/components/timeline';
</script>

<h2 class="text-xl font-bold">ABOUT</h2>

<div class="space-y-4">
	<div>
		<h3 class="text-2xl font-medium">ひつじれれ</h3>
		<p class="text-sm text-gray-600">石川高専 → 金沢大学の3年生</p>
	</div>
	<p>元気に過ごしています</p>
	<div class="flex gap-2">
		<a href="https://twitter.com/HitsujiRere" target="_blank">
			<TwitterBrand size="1.5rem" color="#1DA1F2" />
		</a>
		<a href="https://github.com/HitsujiRere" target="_blank">
			<GithubBrand size="1.5rem" color="#171515" />
		</a>
	</div>
</div>

<div class="space-y-4">
	<h3 class="text-lg font-medium">Award</h3>
	<ul class="space-y-2">
		<li>第2回全国高等専門学校 ディープラーニングコンテスト2021 : 7位</li>
		<li>Hokuriku Innovation Trial-2020 : ICTまちづくり賞</li>
		<li>パソコン甲子園2020 プログラミング部門 : 本選出場</li>
		<li>
			全国高専プログラミングコンテスト 第31回苫小牧大会(2020)
			<ul class="ml-8">
				<li>自由部門 : 特別賞</li>
				<li>パテント審査部門 : 奨励賞</li>
			</ul>
		</li>
	</ul>
</div>

<div class="space-y-4">
	<h3 class="text-lg font-medium">Skill</h3>
	<div class="space-y-2">
		<h4>Language</h4>
		<div class="flex flex-wrap gap-4">
			<SkillCard name="C" icon={skillicons('c')} stars={3} />
			<SkillCard name="C++" icon={skillicons('cpp')} stars={4} />
			<SkillCard name="C#" icon={skillicons('cs')} stars={3} />
			<SkillCard name="TypeScript" icon={skillicons('ts')} stars={4} />
			<SkillCard name="JavaScript" icon={skillicons('js')} stars={5} />
			<SkillCard name="CSS" icon={skillicons('css')} stars={4} />
			<SkillCard name="Python" icon={skillicons('py')} stars={3} />
			<SkillCard name="Rust" icon={skillicons('rust')} stars={2} />
			<SkillCard name="Processing" icon={skillicons('processing')} stars={5} />
		</div>
	</div>
	<div class="space-y-2">
		<h4>Library / Framework</h4>
		<div class="flex flex-wrap gap-4">
			<SkillCard name="React" icon={skillicons('react')} stars={4} />
			<SkillCard name="Next.js" icon={skillicons('next')} stars={4} />
			<SkillCard name="Vue.js" icon={skillicons('vue')} stars={3} />
			<SkillCard name="Unity" icon={skillicons('unity')} stars={2} />
		</div>
	</div>
</div>

<div class="space-y-4">
	<h3 class="text-lg font-medium">Hobby</h3>
	<div class="flex flex-wrap items-center gap-4">
		<SkillCard name="AtCoder" icon="https://img.atcoder.jp/assets/top/img/logo_bk.svg">
			Highest Rate: 1455
		</SkillCard>
		<SkillCard name="🚧追記予定🚧">
			<PersonDiggingSolid slot="icon" size="2.5rem" color="#292524" />
		</SkillCard>
	</div>
</div>

<div class="space-y-4">
	<h3 class="text-lg font-medium">History</h3>
	<div class="ml-2">
		<Timeline>
			<TimelineItem>
				<p class="text-sm text-gray-600">2023-04</p>
				<p>金沢大学に3年次編入</p>
			</TimelineItem>
			<TimelineItem>
				<p class="text-sm text-gray-600">2023-03</p>
				<p>石川工業高等専門学校 卒業</p>
			</TimelineItem>
			<TimelineItem>
				<p>🚧追記予定🚧</p>
			</TimelineItem>
			<TimelineItem>
				<p class="text-sm text-gray-600">2018-04</p>
				<p>石川工業高等専門学校 入学</p>
			</TimelineItem>
		</Timeline>
	</div>
</div>
